FROM amd64/python

ADD addressbook.py /
ADD clean.py /
ADD helpers.py /
ADD new_project.py /
ADD requirements.txt /

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "./new_project.py"]
